### ISSUE TITLE
《Web安全攻防：渗透测试实战指南》怎么样？

### ISSUE THREAD

**Issue by raaww** [riusksk/secbook#10]
Rt

**Comment by riusksk** [comment]
我没看过，翻看了下目录，属于web入门书籍，比较常见的web安全内容，此处暂不作推荐，也不作点评。

**Comment by raaww** [comment]
> 我没看过，翻看了下目录，属于网络入

> 我没看过，翻看了下目录，属于网络入门书籍，比较常见的网络安全内容，此处暂不作推荐，也不作点评。

这个书单大佬还会继续更新吗？

**Comment by riusksk** [comment]
会持续更新

**Comment by raaww** [comment]
> 会持续更新

Web安全除了《黑客攻防技术宝典》还有其他的偏向攻击的Web安全书籍吗？感觉这本书翻译有点烂

**Comment by raaww** [comment]
> 会持续更新

Web安全除了“黑客攻防技术宝典”还有其他的偏向攻击的Web安全入门书籍吗？感觉这本书翻译有点烂

**Comment by riusksk** [comment]
参见原文
