### ISSUE TITLE
鸟哥的私房菜有两本

### ISSUE THREAD

**Issue by wuyuansushen** [riusksk/secbook#11]
如题，是两本都要看，还是只看Linux基础学习篇

**Comment by riusksk** [comment]
另一本是偏向服务器运维的，看个人兴趣和需求，我是没看过。

**Comment by wuyuansushen** [comment]
> 另一本是偏向服务器运维的，看个人兴趣和需求，我是没看过。

好，谢谢_(:з」∠)_做安全的不打算搞运维，那不看了
