### ISSUE TITLE
推荐书籍

### ISSUE THREAD

**Issue by wuyuansushen** [riusksk/secbook#12]
推荐一本php书籍，《代码审计：企业级web安全代码架构》

**Comment by riusksk** [comment]
这书没看过，后面抽空看下，感谢推荐

**Comment by wuyuansushen** [comment]
> 这书没看过，后面抽空看下，感谢推荐

好的，感谢，另外，修正一下，这书原本描述是This is PHP security book,it is not PHP  developer book.
