### ISSUE TITLE
Go language

### ISSUE THREAD

**Issue by wuyuansushen** [riusksk/secbook#13]
Could you add some books about the golang?
I think this language is neccessary for the worker about the informational security!

> Go, also known as Golang, is a statically typed, compiled programming language designed at Google by Robert Griesemer, Rob Pike, and Ken Thompson.Go is syntactically similar to C, but with memory safety, garbage collection, structural typing, and CSP-style concurrency.
There are two major implementations:
Google's self-hosting compiler toolchain targeting multiple operating systems, mobile devices,and WebAssembly.
 gccgo, a GCC frontend.A third party transpiler, GopherJS, compiles Go to JavaScript for front-end web development.
PS:It is quoted from wikipeda.

**Comment by riusksk** [comment]
暂时没学过go语言，就不作推荐了，见谅！

**Comment by wuyuansushen** [comment]
> 暂时没学过go语言，就不作推荐了，见谅！

哦QWQ，好吧，如果以后学了，请你务必推荐一些书籍关于这门语言，十分的感兴趣

**Comment by riusksk** [comment]
好的
