### ISSUE TITLE
二进制入门学习推荐书籍

### ISSUE THREAD

**Issue by xmzyshypnc** [riusksk/secbook#15]
《程序员的自我修养——链接、装载与库》，作者: 俞甲子、石凡。
推荐理由：这本书讲了Linux文件动态链接等基本知识，适合二进制新手学习

**Comment by riusksk** [comment]
感谢推荐，后面我看看先

**Comment by xmzyshypnc** [comment]
okk，多谢师傅的书单和信安学习之路文章的指导~
