### ISSUE TITLE
推荐几本

### ISSUE THREAD

**Issue by houjingyi233** [riusksk/secbook#6]
推荐：
汇编语言第三版，王爽
恶意代码分析实战，michael sikorski
逆向工程核心原理，李承远

**Comment by riusksk** [comment]
这3本书我都没有看过，看过《逆向工程核心原理》的目录，里面的内容比较陈旧，如果他能早个10年出版那算是不错的书籍，只是在这逆向工程书籍满天飞的时代，它就没有多大价值发挥的空间，而且里面的内容在2008年出版的《加密与解密》第3版里面大多已经有了，所以没推荐。

另外两本我后面看看先，如果合适会添加到这列表里面，感谢推荐。

**Comment by riusksk** [comment]
下载电子书翻阅了下，已添加《汇编语言(第3版)》，至于《恶意代码分析实战》里面的内容虽然基础且全面，但跟我推荐的《加密与解密》、《恶意软件分析诀窍与工具箱》的太多交集，因此暂不作推荐。
