### ISSUE TITLE
web应用安全权威指南【日】德丸浩

### ISSUE THREAD

**Issue by cocosec** [riusksk/secbook#7]
这本书日本写的，web应用安全入门教材，可能因为日文翻译成中文要比英文翻译成中文更接近原意，比黑客攻防技术宝典web实战篇要更容易读懂和理解。

**Comment by riusksk** [comment]
感谢推荐，这书比较基础，感觉在深度和广度上都不够，而且不太适合作为渗透测试的指导书籍，如果看过《黑客攻防技术宝典web实战篇》的话，其实也没必要看这书。
个人看法，遵循自己喜好就好！
